#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_DIR="$ROOT/agent-sources"
SKILLS_DIR="$ROOT/skills"

fail() {
  echo "agent-skills_test: $*" >&2
  exit 1
}

count=0
for src in "$SRC_DIR"/*.md; do
  [ -e "$src" ] || fail "no source agent markdown files found"

  name="$(sed -n 's/^name:[[:space:]]*//p' "$src" | head -1)"
  [ -n "$name" ] || fail "missing name in $src"

  skill="$SKILLS_DIR/$name/SKILL.md"
  meta="$SKILLS_DIR/$name/agents/openai.yaml"

  [ -f "$skill" ] || fail "missing generated agent skill: $skill"
  [ -f "$meta" ] || fail "missing generated openai.yaml: $meta"

  grep -q "^name: $name$" "$skill" || fail "$skill missing exact name frontmatter"
  grep -q "Generated by tools/generate-agent-skills.mjs from agent-sources/$name.md" "$skill" || {
    fail "$skill missing generated marker"
  }
  grep -q "Read \`../../agent-sources/$name.md\`" "$skill" || {
    fail "$skill does not point to source agent"
  }
  grep -q 'interface:' "$meta" || fail "$meta missing interface block"
  default_prompt_needle="Use \$$name "
  grep -Fq "$default_prompt_needle" "$meta" || {
    fail "$meta default prompt must mention $default_prompt_needle"
  }

  count=$((count + 1))
done

[ "$count" -gt 0 ] || fail "expected at least one generated agent skill"

echo "agent-skills_test: verified $count agent skill wrappers"
