#!/usr/bin/env bash
set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="${1:-$PWD}"
SRC_DIR="$PLUGIN_ROOT/.codex/agents"
DEST_DIR="$PROJECT_ROOT/.codex/agents"

[ -d "$SRC_DIR" ] || {
  echo "install-codex-agents: missing generated agent directory: $SRC_DIR" >&2
  exit 1
}

mkdir -p "$DEST_DIR"

installed=0
updated=0
skipped=0

for src in "$SRC_DIR"/*.toml; do
  [ -e "$src" ] || continue
  dest="$DEST_DIR/$(basename "$src")"

  if [ ! -e "$dest" ]; then
    cp "$src" "$dest"
    installed=$((installed + 1))
    continue
  fi

  if grep -qE 'Generated by tools/generate-codex-agents\.mjs|Converted from upstream agent source' "$dest"; then
    cp "$src" "$dest"
    updated=$((updated + 1))
    continue
  fi

  echo "install-codex-agents: skipped user-owned custom agent: $dest" >&2
  skipped=$((skipped + 1))
done

echo "Codex custom agents installed=$installed updated=$updated skipped=$skipped dest=$DEST_DIR"
